### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by bigjuanpa** [maragelis/micropython_paradox#8]
Hi maragelis,
I was trying to test the new paradox code and I was not able to make it work.
First there is a missing utelegram file, I fix that copying the file from the test branch.
After that the code works, but I was only able to connect to MQTT and get the version and IP of the device.
The alarm was not sending any data and the web index.html was not up.
Maybe I did something wrong, it is my first time working with micropython on esp32.
On the esp32 I connect the rx2 and tx2 that is correct right ?

let me know if you have any tip for me.
Thanks

**Comment by maragelis** [comment]
Hi,  I updated the main.py file and removed the bug thanks for that. You can keep the chip connected to thonny, you should get messages below in the repl screen.

**Comment by maragelis** [comment]
closed#
